# Generated by Django 4.2 on 2025-05-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetTourSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentid', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('addr1', models.CharField(blank=True, max_length=255)),
                ('addr2', models.CharField(blank=True, max_length=255)),
                ('areacode', models.CharField(blank=True, max_length=10)),
                ('sigungucode', models.CharField(blank=True, max_length=10)),
                ('mapx', models.FloatField(blank=True, null=True)),
                ('mapy', models.FloatField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=100)),
                ('firstimage', models.URLField(blank=True)),
                ('contenttypeid', models.CharField(blank=True, max_length=10)),
                ('cat1', models.CharField(blank=True, max_length=10)),
                ('cat2', models.CharField(blank=True, max_length=10)),
                ('cat3', models.CharField(blank=True, max_length=20)),
                ('overview', models.TextField(blank=True)),
                ('createdtime', models.CharField(blank=True, max_length=20)),
                ('modifiedtime', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
